spring.application.name=bima

spring.datasource.url=jdbc:postgresql://localhost:5434/bima
spring.datasource.username=postgres
spring.datasource.password=1221
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false